version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21

  pre-build:
    commands:
      - aws --version
      - echo "Docker Login"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 590184051080.dkr.ecr.ap-south-1.amazonaws.com
  
  build:
    commands: 
      - echo "Docker Build and Push"
      - docker build -t react .
      - docker tag react:latest 590184051080.dkr.ecr.ap-south-1.amazonaws.com/react:latest
      - docker push 590184051080.dkr.ecr.ap-south-1.amazonaws.com/react:latest
artifacts:
  files:
    - '**/*' # Include all files in the artifact

cache:
  paths:
    - node_modules/ # Cache the node_modules directory to speed up subsequent builds
