version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: 'aakarshak1/react_project'
    ports:
      - "3000:4173"
    environment:
      - NODE_ENV=development
